server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Если страница не найдена на сервере, Nginx перенаправит запрос на index.html,
        # и дальше роутингом займется сам React.
        try_files $uri $uri/ /index.html;
    }
}
