version: '3.8'

services:
  #БД PostgreSQL
  postgres_db:
    image: postgres:16-alpine
    container_name: egov_postgres
    restart: always
    environment:
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: db_secure_password123
      POSTGRES_DB: egov_db
    ports:
      - "5432:5432" # Пробрасываем порт наружу, чтобы мы могли подключиться через pgAdmin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  #БЭКЕНД (C# .NET API)
  backend:
    build:
      context: ./backend # Путь к папке с C# проектом
      dockerfile: Dockerfile
    container_name: egov_backend
    restart: always
    ports:
      - "8080:8080" # Бэкенд будет доступен по адресу http://localhost:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # Заменяем localhost в строке подключения на имя контейнера базы данных (postgres_db)
      - ConnectionStrings__DefaultConnection=Host=postgres_db;Port=5432;Database=egov_db;Username=db_user;Password=db_secure_password123
      # Сюда же можно вписать настройки JWT из вашего Program.cs, чтобы не хранить их в коде:
    depends_on:
      - postgres_db # Бэкенд начнет загрузку только после старта базы данных

  #ФРОНТЕНД (React + Vite + Nginx)
  frontend:
    build:
      context: ./frontend # Путь к папке с React проектом
      dockerfile: Dockerfile
    container_name: egov_frontend
    restart: always
    ports:
      - "3000:80" # Фронтенд будет доступен в браузере по адресу http://localhost:3000
    depends_on:
      - backend

# Объявляем постоянное хранилище для базы данных
volumes:
  postgres_data:
