services:
  db:
    image: postgres:15-alpine
    container_name: egov_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_secure_password #текущий пароль от БД
      POSTGRES_DB: EGOV_DB1 # Имя базы данных
    ports:
      - "5432:5432" # Пробрасываем порт наружу, чтобы pgAdmin на ПК мог подключаться к контейнеру
    volumes:
      - postgres_data:/var/lib/postgresql/data # Данные не сотрутся при перезапуске докера

  #СЕРВИС БЭКЕНДА
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: egov_backend_api
    restart: always
    ports:
      - "5170:5170"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=EGOV_DB1;Username=postgres;Password=your_secure_password;
    depends_on:
      - db # Бэкенд начнет запускаться только после того, как поднимется база данных

  #СЕРВИС ФРОНТЕНДА
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: egov_frontend_app
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
